#!/bin/bash
#SBATCH --job-name=misinfo_perception_modeling
#SBATCH --mail-user=ashkank@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=5:00:00
#SBATCH --account=mihalcea0
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:4
#SBATCH --partition=gpu
#SBATCH --output=/home/%u/logs/%x-%j.log
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=8g


source /home/ashkank/.bashrc
conda activate perceptron
cd /home/ashkank/perception/src
python train_perception_modeling.py default gen
python train_perception_modeling.py bigDataSmallModel gen
python train_perception_modeling.py bigDataMediumModel load
python train_perception_modeling.py bigDataBigModel load