python train_perception_modeling.py bigDataSmallModel load &&
python evaluate_perception_modeling.py bigDataSmallModel &&
python train_perception_modeling.py bigDataSmallModelLabelsOnly load &&
python evaluate_perception_modeling.py bigDataSmallModelLabelsOnly