#!/bin/bash
#SBATCH --job-name=misinfo_perception_modeling
#SBATCH --mail-user=ashkank@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=4:00:00
#SBATCH --account=mihalcea98
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:2
#SBATCH --partition=spgpu
#SBATCH --output=/home/%u/logs/%x-%j.log
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=16g


source /home/ashkank/.bashrc
conda activate perceptron
cd /home/ashkank/perception/src
python train_perception_modeling.py bigDataMediumModel gen
python train_perception_modeling.py bigDataMediumModel load
python train_perception_modeling.py bigDataBigModel load